Aruiz/feat/86b2uqajp/add mui to boilerplate
Krysthecoder/magicooker pull request #5
Opened 2024-11-16 02:49 UTC by Ralexs0096

**Hello Team:**

### Description
This Pull Request addresses the following updates and improvements:

- Remove the default configuration of tailwind in favor of using MUI.
- Add MUI and its dependencies (roboto font)
- Create an initial component using MUI Components. 

- **Testing:**
N/A

Please review the changes at your convenience. Your feedback would be greatly appreciated!

2024-11-16 03:07 UTC, AlvisonHunterArnuero requested changes
nit, add these as well if seen fit, please.

2024-11-16 03:07 UTC, AlvisonHunterArnuero commented on .gitignore
> +.env
```suggestion
.env
.env.local
.env.*.local
```

2024-11-16 17:48 UTC, Ralexs0096 commented on .gitignore
> +.env
applied

2024-11-17 01:25 UTC, AlvisonHunterArnuero approved these changes
LGTM!

2024-11-17 23:09 UTC, merged